In [37]:
obs1 = [-1 -1 -1 -1 -1 -1 -1 -1 +1 +1 +1 +1 +1 +1 +1 +1; 
                -1 -1 -1 -1 +1 +1 +1 +1 -1 -1 -1 -1 +1 +1 +1 +1;
        -1 -1 +1 +1 -1 -1 +1 +1 -1 -1 +1 +1 -1 -1 +1 +1;
    -1 +1 -1 +1 -1 +1 -1 +1 -1 +1 -1 +1 -1 +1 -1 +1]


4×16 Matrix{Int64}:
 -1  -1  -1  -1  -1  -1  -1  -1   1   1   1   1   1   1   1  1
 -1  -1  -1  -1   1   1   1   1  -1  -1  -1  -1   1   1   1  1
 -1  -1   1   1  -1  -1   1   1  -1  -1   1   1  -1  -1   1  1
 -1   1  -1   1  -1   1  -1   1  -1   1  -1   1  -1   1  -1  1

In [38]:
tau = 0.5

0.5

In [39]:
k = 300

300

In [40]:
q = zeros(16)
for j = 1:16
   q[j] = (1 / 16) * (1 + obs1[1, j] * obs1[2, j] * tau)
end

In [41]:
q

16-element Vector{Float64}:
 0.09375
 0.09375
 0.09375
 0.09375
 0.03125
 0.03125
 0.03125
 0.03125
 0.03125
 0.03125
 0.03125
 0.03125
 0.09375
 0.09375
 0.09375
 0.09375

In [42]:
mean = k *q

16-element Vector{Float64}:
 28.125
 28.125
 28.125
 28.125
  9.375
  9.375
  9.375
  9.375
  9.375
  9.375
  9.375
  9.375
 28.125
 28.125
 28.125
 28.125

In [43]:
using LinearAlgebra # this package comes with Julia, no need to install it

In [44]:
meandia = diagm(q)

16×16 Matrix{Float64}:
 0.09375  0.0      0.0      0.0      …  0.0      0.0      0.0      0.0
 0.0      0.09375  0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.09375  0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.09375     0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0      …  0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0      …  0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.09375  0.0      0.0      0.0
 0.0      0.0      0.0      0.0         0.0      0.093

In [45]:
b = transpose(q)

1×16 transpose(::Vector{Float64}) with eltype Float64:
 0.09375  0.09375  0.09375  0.09375  …  0.09375  0.09375  0.09375  0.09375

In [46]:
c = q * b

16×16 Matrix{Float64}:
 0.00878906  0.00878906  0.00878906  …  0.00878906  0.00878906  0.00878906
 0.00878906  0.00878906  0.00878906     0.00878906  0.00878906  0.00878906
 0.00878906  0.00878906  0.00878906     0.00878906  0.00878906  0.00878906
 0.00878906  0.00878906  0.00878906     0.00878906  0.00878906  0.00878906
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969  …  0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969  …  0.00292969  0.00292969  0.00292969
 0.00292969  0.00292969  0.00292969     0.00292969  0.00292969  0.00292969
 0.00878906  0.00878906  0.00878906     0.00878906  0.00878906  0.00878906
 0

In [47]:
d = meandia -c 

16×16 Matrix{Float64}:
  0.0849609   -0.00878906  -0.00878906  …  -0.00878906  -0.00878906
 -0.00878906   0.0849609   -0.00878906     -0.00878906  -0.00878906
 -0.00878906  -0.00878906   0.0849609      -0.00878906  -0.00878906
 -0.00878906  -0.00878906  -0.00878906     -0.00878906  -0.00878906
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969  …  -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969  …  -0.00292969  -0.00292969
 -0.00292969  -0.00292969  -0.00292969     -0.00292969  -0.00292969
 -0.00878906  -0.00878906  -0.00878906     -0.00878906  -0.00878906
 -0.00878906  -0.00878906  -0.00878906     -0.00878906  -0.00878906
 -0.00878906  -0.00878906

In [48]:
cov = k * d

16×16 Matrix{Float64}:
 25.4883    -2.63672   -2.63672   …  -2.63672   -2.63672   -2.63672
 -2.63672   25.4883    -2.63672      -2.63672   -2.63672   -2.63672
 -2.63672   -2.63672   25.4883       -2.63672   -2.63672   -2.63672
 -2.63672   -2.63672   -2.63672      -2.63672   -2.63672   -2.63672
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906  …  -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906  …  -0.878906  -0.878906  -0.878906
 -0.878906  -0.878906  -0.878906     -0.878906  -0.878906  -0.878906
 -2.63672   -2.63672   -2.63672      -2.63672   -2.63672   -2.63672
 -2.63672   -2.63672   -2.63672      25.4883    -2.63672   -2.63672
 -2.63672   -2.63

In [49]:
freq1 =[26.18595552 19.88178106 32.3619518  25.1850168  11.72939597  4.96815609 8.61220286  7.62459227 11.13078244 16.30505883  8.51878733  7.4611995 29.28236207 27.01672445 30.94814749 32.78788534] 

1×16 Matrix{Float64}:
 26.186  19.8818  32.362  25.185  …  29.2824  27.0167  30.9481  32.7879

In [50]:
using Pkg

In [51]:
Pkg.add("JuMP")

   Resolving package versions...
  No Changes to `C:\Users\21068\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\21068\.julia\environments\v1.6\Manifest.toml`


In [66]:
using Ipopt,JuMP
model = Model(Ipopt.Optimizer)
@variable(model,x[1:16,1:5]>=0)
i = 1
for j in 1:16
    @constraint(model,x[j,i]<=1)
end
i = 2
for j in 1:16
    @constraint(model,x[j,i]<=1)
end
i = 3
for j in 1:16
    @constraint(model,x[j,i]>=1)
end
i = 4
for j in 1:16
    @constraint(model,x[j,i]>=1)
end
i = 5
for j in 1:16
    @constraint(model,x[j,i]<=1)
end
for j in 1:16
    @NLconstraint(model,x[j,1]*x[j,2]*x[j,5] == 0.5)
end
@NLobjective(model, Min, sum(q[i]*((0.5-obs1[1,i]*obs1[3,i]*x[i,1]*x[i,3]
                -obs1[2,i]*obs1[4,i]*x[i,2]*x[i,4]
                -obs1[1,i]*obs1[4,i]*x[i,1]*x[i,5]*x[i,4]
                -obs1[1,i]*obs1[4,i]*x[i,1]*x[i,5]*x[i,4])^2) for i in 1:16))
optimize!(model)
status = termination_status(model)

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:       48
Number of nonzeros in inequality constraint Jacobian.:       80
Number of nonzeros in Lagrangian Hessian.............:      336

Total number of variables............................:       80
                     variables with only lower bounds:       80
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:       16
Total number of inequality constraints...............:       80
        inequality constraints with only lower bounds:       32
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:       48

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.5000002e-01 9.90e-01 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00  

LOCALLY_SOLVED::TerminationStatusCode = 4

In [67]:
println(objective_value(model))

2.4999999243538875


In [73]:
for i in 1:16
    for j in 1:5
        print(" ",round(value(x[i,j]),digits =2))
    end
    println()
    a = value(x[i,1])
    b = value(x[i,2])
    c =  value(x[i,5])
    println("the multiple of 125 is ", a*b*c)
end

 0.5 1.0 1.0 1.0 1.0
the multiple of 125 is 0.5
 0.82 0.79 24.73 9.55 0.78
the multiple of 125 is 0.4999999999998011
 0.82 0.79 21.25 8.67 0.78
the multiple of 125 is 0.4999999999999595
 0.5 1.0 1.0 1.0 1.0
the multiple of 125 is 0.5
 0.5 1.0 1.0 10.28 1.0
the multiple of 125 is 0.4999999999066841
 0.8 0.76 12.2 17.08 0.81
the multiple of 125 is 0.49999999999973116
 0.77 0.9 8.76 35.81 0.72
the multiple of 125 is 0.49999999999856803
 0.5 1.0 1.0 12.45 1.0
the multiple of 125 is 0.5
 0.5 1.0 1.0 12.45 1.0
the multiple of 125 is 0.5
 0.77 0.9 8.76 35.81 0.72
the multiple of 125 is 0.49999999999856803
 0.8 0.76 12.2 17.08 0.81
the multiple of 125 is 0.49999999999973116
 0.5 1.0 1.0 10.28 1.0
the multiple of 125 is 0.4999999999066841
 0.5 1.0 1.0 1.0 1.0
the multiple of 125 is 0.5
 0.82 0.79 21.25 8.67 0.78
the multiple of 125 is 0.4999999999999595
 0.82 0.79 24.73 9.55 0.78
the multiple of 125 is 0.4999999999998011
 0.5 1.0 1.0 1.0 1.0
the multiple of 125 is 0.5


In [69]:
 print(round(value(x[1,2]),digits =2))

1.0